### ISSUE TITLE
Add auto-batching client

### ISSUE THREAD

**Issue by rbino** [rbino/tigerbeetlex#37]
The existing stateful client (or possibly a separate one) can support automatically batching incoming requests, to allow collecting requests from multiple services maximizing TigerBeetle capabilities (see [here](https://docs.tigerbeetle.com/design/client-requests/#batching-events)).

The behaviour can be a client that waits until a batch size is reached _or_ a timeout occurs, whichever comes first.

**Comment by lessless** [comment]
Hey @rbino,

Thank you for your work on the TB client. I'm just catching up with all its capabilities and and noticed that they moved away document you linked in the description. 

Thanks!

**Comment by rbino** [comment]
Hey @lessless, thanks for the heads up, I'll see if I can find a new reference.

I've also done some experimenting with auto-batching for the TigerBeetle Hackaton at Interledger Summit 2023, you can find a video about this [here](https://www.youtube.com/watch?v=Pp0payibvJI) and the code is [here](https://github.com/tigerbeetle/hackathon-2023/pull/2)

**Comment by rbino** [comment]
The native TigerBeetle client already does this automatically now (see https://github.com/tigerbeetle/tigerbeetle/pull/1257), so there's no need to support it at the Elixir client level.

Closing this.

**Comment by lessless** [comment]
> Hey @lessless, thanks for the heads up, I'll see if I can find a new reference.
> 
> I've also done some experimenting with auto-batching for the TigerBeetle Hackaton at Interledger Summit 2023, you can find a video about this [here](https://www.youtube.com/watch?v=Pp0payibvJI) and the code is [here](https://github.com/tigerbeetle/hackathon-2023/pull/2)

Thanks for sharing @rbino ! That's was a great presentation. It nicely matches the TB engineering environment. 

I wish I would have a chance to work with it in prod one day :)
