### ISSUE TITLE
Update README.md > tigerbeetle setup steps

### ISSUE THREAD

**Issue by jeryldev** [rbino/tigerbeetlex#48]
Update README.md steps to setup the tigerbeetle for testing. The updated steps are based on https://docs.tigerbeetle.com/quick-start/

```bash
$ git clone --recurse-submodules https://github.com/rbino/tigerbeetlex.git 
$ cd tigerbeetlex/src/tigerbeetle
$ scripts/install_zig.sh
$ zig/zig build
$ ./tigerbeetle version
$ ./tigerbeetle format --cluster=0 --replica=0 --replica-count=1 --development 0_0.tigerbeetle
$ ./tigerbeetle start --addresses=3000 --development 0_0.tigerbeetle
```

I tried to file a PR but I cannot create a branch yet so I'm filing an issue instead. 😅

**Comment by rbino** [comment]
I've updated the README with the steps to download a prebuilt version of TigerBeetle, closing this
